# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'KjemiaQuiz' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for KjemiaQuiz
  pod 'GoogleToolboxForMac', '~> 2.1'
  pod 'Google-Mobile-Ads-SDK'


  target 'KjemiaQuizTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

