# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'KjemiaQuiz' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for KjemiaQuiz
  # Required by RNFirebase
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'GoogleToolboxForMac', '~> 2.1'
  pod 'Google-Mobile-Ads-SDK'

  target 'KjemiaQuiz-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-in-app-utils', :path => '../node_modules/react-native-in-app-utils'

  end

  target 'KjemiaQuizTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

